// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mltbykgyncoxqyqwosyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1sdGJ5a2d5bmNveHF5cXdvc3liIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3OTc2NjcsImV4cCI6MjA2NDM3MzY2N30.FEjFTPQo0HIcAPQnpnrkunyk3JToj9R-ATY1CCWO7iI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);